USE ArtFeed;
GO

ALTER TABLE PerfilArtista
ALTER COLUMN preco NVARCHAR(50) NULL;
GO

USE ArtFeed;
GO

SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('Clientes', 'Artistas')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

